### ISSUE TITLE
issue installing pycurl

### ISSUE THREAD

**Issue by smaster7772** [shamspias/customizable-gpt-chatbot#19]
I'm getting this issue when trying to install the requirements, any help would be appreciated. 

````
Collecting pycurl (from -r requirements.txt (line 18))
  Using cached pycurl-7.45.2.tar.gz (234 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 10
  ╰─> [1 lines of output]
      Please specify --curl-dir=/path/to/built/libcurl
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
````

**Comment by shamspias** [comment]
Please install 

sudo apt install python3-dev 
sudo apt install libcurl4-openssl-dev gcc libssl-dev
pip install --upgrade pip setuptools
pip install pycurl

**Comment by smaster7772** [comment]
I'm on windows 11

**Comment by shamspias** [comment]
I don't test it in Windows 11 but the issue about installing pycurl in Windows 11 maybe solved with this

active your virtualenv
install
pip install wheel

download the wheel pack for pycurl from here : `https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl`
example: `pycurl‑7.45.1‑cp311‑cp311‑win_amd64.whl`

then install it
`pip install pycurl‑7.43.0.6‑cp38‑cp38‑win_amd64.whl`

hope this might solve your issue.

besides you can use redis for local test instead of using SQS.

you don't need pycurl if you are not using AWS SQS here.

Thanks
