### ISSUE TITLE
Ui chat?

### ISSUE THREAD

**Issue by ivan-vilches** [shamspias/customizable-gpt-chatbot#24]
I think i ran the deploy the project well on mac. But the only i can see is swagger on localhost:8000 
No chat design or ui functionality?
Thanks

**Comment by shamspias** [comment]
This project is backed only.
you can make your Own UI based on that.
will write endpoint and postman request soon.

**Comment by simon555** [comment]
HI,

I have completed installation but I am not sure how to use this repo ? How can I train chatbots or converse with them ?

Thank you!
Simon

**Comment by shamspias** [comment]
it's full backend.
I will update readme later how to use it

**Comment by simon555** [comment]
The backend is working as is ?

**Comment by shamspias** [comment]
yep backend working perfectly.

**Comment by simon555** [comment]
Thank you for your quick answer!! :-)

I have no experience in dealing with Django backend unfortunately, do you know when you could push the updated readme ?

Also, not sure if it's relevant but when I click on 'login' in the swagger page I get a 404 error

**Comment by shamspias** [comment]
ok, I will,
about the swagger login issue can you share the error, please?

**Comment by simon555** [comment]
Sure thing : 

On the Swagger page, when I click on 'Django Login' I get this



Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/accounts/login/?next=/
Using the URLconf defined in config.urls, Django tried these URL patterns, in this order:

admin/
training-model/
oauth2/
social-auth/
api-auth/
api/v1/users/
api/v1/site-settings/
api/v1/chatbot/
[name='schema-swagger-ui']
redoc/ [name='schema-redoc']
The current path, accounts/login/, didn’t match any of these.

You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by shamspias** [comment]
well you can log in use 
http://127.0.0.1:8000/admin

**Comment by simon555** [comment]
Thank you!

What should be the admin username and password ?

**Comment by shamspias** [comment]
you need basic knowledge of Django for it.

have to migrate the database then create superuser
then use that username and password

**Comment by simon555** [comment]
Okay, I'll get up to speed on Django, thanks for the hint! :-)

Do you know when you will be able to push the new readme ?

**Comment by shamspias** [comment]
It will be late currently I am researching another vector database to integrate with that project maybe once the project completely done.
